/**
 * Names this corpus has used, and what each resolves to.
 *
 * Identifiers here are a published contract: `packages/rules/README.md` tells
 * consumers to join on a rule id, store it, and expect it not to change. When
 * one does change, the old name has to keep resolving or every dataset
 * published under it is stranded — that is the guidelines' own rule, that a
 * deprecated name is not an incorrect one.
 *
 * So resolution happens on the way IN, at the two places a name arrives from
 * outside: an edition declaring its riwayah, and an annotation set naming the
 * rules its spans belong to. Nothing here writes an old name; it only reads one.
 *
 * The table is `packages/rules/aliases.json`, generated by joining this corpus
 * against the `tajwid_rules` registry in quran-ws/guidelines — a registry that
 * was itself generated from this corpus, so every row already records the slug
 * it is replacing. No name here was invented.
 *
 * Nothing is renamed yet. This is the mechanism that makes renaming survivable,
 * and it is deliberately in place before the rename rather than after it.
 */

import table from '../../rules/aliases.json' with { type: 'json' }

interface AliasTable {
  readonly riwayah: Readonly<Record<string, string>>
  readonly hukums: Readonly<Record<string, string>>
}

const aliases = table as unknown as AliasTable

/**
 * The canonical name for a riwayah, given any spelling this corpus has used.
 * Unknown names are returned unchanged: this resolves, it does not validate.
 */
export function resolveRiwayah(name: string): string {
  return aliases.riwayah[name] ?? name
}

/** True when two riwayah names are the same riwayah, however each is spelled. */
export function sameRiwayah(a: string, b: string): boolean {
  return resolveRiwayah(a) === resolveRiwayah(b)
}

/**
 * The canonical form of a rule id, given any spelling this corpus has used.
 *
 * A rule id is `<hukum>.<n>`, so it moves when its hukum does and the numeric
 * suffix is carried across unchanged.
 */
export function resolveRuleId(id: string): string {
  const dot = id.indexOf('.')
  const hukum = dot === -1 ? id : id.slice(0, dot)
  const canonical = aliases.hukums[hukum]
  if (canonical === undefined) {
    return id
  }
  return dot === -1 ? canonical : canonical + id.slice(dot)
}

/**
 * Both spellings of a rule id, so a lookup keyed on either finds it. Returned
 * in the order tried: the id as given, then its canonical form.
 */
export function ruleIdSpellings(id: string): readonly string[] {
  const canonical = resolveRuleId(id)
  return canonical === id ? [id] : [id, canonical]
}
